baseURL = 'https://stevenshim.github.io/'
languageCode = 'ko-kr'
title = '개발 못하는 개발자, 인프라 모르는 운영자'
theme = "m10c"

[params]
author = 'Hojin Shim'
description = 'Site Reliability Engineer'
avatar = './images/me.jpg'
favicon = './favicon.ico'


#[[params.social]]
#icon = "github"
#name = "My Github"
#url = "https://github.com/vaga"
